In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\Users\odc\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\odc\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\odc\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\odc\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\odc\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [13]:
import pandas as pd
import numpy as np

Partie 1 – Series

In [2]:
# 1) Créer une Series contenant 4 températures
temp_series = pd.Series([22.5, 25.0, 28.3, 21.1])

# 2) Afficher son index
print(temp_series.index)

# 3) Afficher la 1ère valeur
print(temp_series.iloc[0])

# 4) Afficher la dernière valeur
print(temp_series.iloc[-1])

# 5) Créer, de deux façons différentes, une Series avec index d'heures
heures = ["12h", "13h", "14h", "15h"]
vals = [22.5, 25.0, 28.3, 21.1]

# Méthode A
series_a = pd.Series(vals, index=heures)

# Méthode B
series_b = pd.Series({"12h": 22.5, "13h": 25.0, "14h": 28.3, "15h": 21.1})

# 6) Afficher la 1ère et la dernière valeur
print("1ère :", series_a.iloc[0], "| Dernière :", series_a.iloc[-1])

RangeIndex(start=0, stop=4, step=1)
22.5
21.1
1ère : 22.5 | Dernière : 21.1

Partie 2 – DataFrame

In [5]:
# 1) Créer et afficher df_test
data = {
    "capteur": ["C001", "C002", "C003"],
    "temperature": [24.5, 25.1, 26.3],
    "humidite": [65, 67, 70],
}
df_test = pd.DataFrame(data)
print(df_test)

# 2) Importer le dataset mesures_capteurs.csv dans df
df = pd.read_csv("../data/mesures_capteurs.csv")

# 3) Afficher les dimensions de df
print(df.shape)

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70
(605, 9)

In [10]:
#Partie 3 – Exploration
#1. Premières lignes
df.head()
#2. Les 10 premières lignes
df.head(10)
#3. Dernières lignes
df.tail()
#4. Nombre de lignes
print(len(df))
#5. Nombre de colonnes
print(df.shape[1])
#6) Afficher les noms des colonnes
print(df.columns.tolist())
#7) Afficher les informations générales
df.info()
#8) Afficher les statistiques descriptives
df.describe()

605
9
['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature', 'humidite', 'pression', 'consommation', 'etat']
<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    str
 1   date_heure    605 non-null    str
 2   id_capteur    605 non-null    str
 3   batiment      605 non-null    str
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    str
dtypes: float64(4), str(5)
memory usage: 42.7 KB

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000

Partie 4 – Sélection

In [11]:
#1) Sélectionner la colonne "temperature"
df["temperature"]
#2) Sélectionner les colonnes "temperature", "humidite", "pression" et "consommation"
df[
    ["temperature", "humidite", "pression", "consommation"]
]
#3) Sélectionner les 5 premières lignes avec loc
df.loc[:4]
#4) Sélectionner les 5 premières lignes et les 4 premières colonnes avec iloc
df.iloc[:5, :4]

  id_mesure           date_heure id_capteur batiment
0     M0413  2026-01-22 04:00:00       C005     B002
1     M0290  2026-01-17 01:00:00       C002     B001
2     M0077  2026-01-08 04:00:00       C005     B002
3     M0079  2026-01-08 06:00:00       C007     B003
4     M0183  2026-01-12 14:00:00       C003     B001

Partie 5 – Manipulation des colonnes

In [15]:
#1) Ajouter la colonne "temperature_fahrenheit"
df["temperature_fahrenheit"] = (
    df["temperature"] * 9 / 5 + 32
)
df.head()
#2) Ajouter la colonne "niveau_temperature" pour catégoriser la température en "Élevée" (température > 30) ou "Normale". On peut utiliser la méthode where() de numpy
df["niveau_temperature"] = np.where(
    df["temperature"] > 30,
    "Élevée",
    "Normale"
)
df[["temperature", "niveau_temperature"]].head()
#3) Renommer la colonne "humidite" en "humidite_relative"
df.rename(
    columns={"humidite": "humidite_relative"},
    inplace=True
)
#4) Supprimer la colonne "temperature_fahrenheit"
df.drop(
    columns=["temperature_fahrenheit"],
    inplace=True
)

Partie 6 – Filtrage

In [16]:
#1) Récupérer uniquement les lignes telles que température > 30
df_temperature_elevee = df[
    df["temperature"] > 30
]

print(df_temperature_elevee)
#2) Récupérer uniquement les lignes telles que température > 30 et humidité > 70
df_filtre = df[
    (df["temperature"] > 30) &
    (df["humidite_relative"] > 70)
]

print(df_filtre)

    id_mesure           date_heure id_capteur batiment  temperature  \
7       M0132  2026-01-10 11:00:00       C012     B004        31.21
43      M0575  2026-01-28 22:00:00       C011     B004        34.72
47      M0082  2026-01-08 09:00:00       C010     B004        32.46
63      M0064  2026-01-07 15:00:00       C004     B002        31.19
79      M0275  2026-01-16 10:00:00       C011     B004        31.74
88      M0288  2026-01-16 23:00:00       C012     B004        30.06
103     M0311  2026-01-17 22:00:00       C011     B004        30.83
112     M0149  2026-01-11 04:00:00       C005     B002        31.46
118     M0365  2026-01-20 04:00:00       C005     B002        32.90
129     M0592  2026-01-29 15:00:00       C004     B002        33.60
137     M0076  2026-01-08 03:00:00       C004     B002        31.18
145     M0503  2026-01-25 22:00:00       C011     B004        30.57
146     M0118  2026-01-09 21:00:00       C010     B004        30.32
165     M0323  2026-01-18 10:00:00       C011     B004        33.01
168     M0276  2026-01-16 11:00:00       C012     B004        30.39
169     M0546  2026-01-27 17:00:00       C006     B002        32.36
174     M0405  2026-01-21 20:00:00       C009     B003        31.74
210     M0588  2026-01-29 11:00:00       C012     B004        31.51
211     M0370  2026-01-20 09:00:00       C010     B004        33.29
224     M0303  2026-01-17 14:00:00       C003     B001        30.84
243     M0416  2026-01-22 07:00:00       C008     B003        30.16
246     M0312  2026-01-17 23:00:00       C012     B004        30.13
251     M0114  2026-01-09 17:00:00       C006     B002        31.85
257     M0378  2026-01-20 17:00:00       C006     B002        31.99
264     M0191  2026-01-12 22:00:00       C011     B004        30.75
274     M0046  2026-01-06 21:00:00       C010     B004        30.92
280     M0585  2026-01-29 08:00:00       C009     B003        31.30
322     M0120  2026-01-09 23:00:00       C012     B004        30.19
356     M0574  2026-01-28 21:00:00       C010     B004        30.61
362     M0396  2026-01-21 11:00:00       C012     B004        30.57
385     M0126  2026-01-10 05:00:00       C006     B002        30.09
398     M0514  2026-01-26 09:00:00       C010     B004        30.48
401     M0586  2026-01-29 09:00:00       C010     B004        31.44
404     M0598  2026-01-29 21:00:00       C010     B004        30.37
417     M0432  2026-01-22 23:00:00       C012     B004        30.38
437     M0286  2026-01-16 21:00:00       C010     B004        32.16
438     M0558  2026-01-28 05:00:00       C006     B002        32.56
447     M0170  2026-01-12 01:00:00       C002     B001        31.15
488     M0431  2026-01-22 22:00:00       C011     B004        30.14
492     M0552  2026-01-27 23:00:00       C012     B004        30.24
500     M0062  2026-01-07 13:00:00       C002     B001        30.39
502     M0048  2026-01-06 23:00:00       C012     B004        58.70
505     M0268  2026-01-16 03:00:00       C004     B002        30.34
520     M0063  2026-01-07 14:00:00       C003     B001        32.72
541     M0202  2026-01-13 09:00:00       C010     B004        30.86
558     M0346  2026-01-19 09:00:00       C010     B004        30.68

     humidite_relative  pression  consommation    etat niveau_temperature
7                60.57   1024.64        285.92      OK             Élevée
43               57.50   1008.94        266.22  ALERTE             Élevée
47               72.31   1000.42        276.99  ALERTE             Élevée
63               55.13   1011.04        264.98      OK             Élevée
79               69.95   1020.79        335.89      OK             Élevée
88               75.30   1014.47        323.32      OK             Élevée
103              54.99   1026.47        256.11      OK             Élevée
112              48.48   1002.75        210.94      OK             Élevée
118              65.91   1027.28        246.08  ALERTE             Élevée
129              79.80   1021.96        212.55  ALERTE             Élevée
137              49.66   1019.91        215.22      OK             Élevée
145              71.26   1002.88        359.97      OK             Élevée
146                NaN   1015.78        261.68      OK             Élevée
165              73.24   1014.36        260.24  ALERTE             Élevée
168              71.14   1017.79        303.38      OK             Élevée
169              67.34    998.10        184.89  ALERTE             Élevée
174              47.23   1015.59        115.79      OK             Élevée
210              72.49   1018.21        307.97      OK             Élevée
211              50.43   1009.87        356.76  ALERTE             Élevée
224              67.98   1020.09        157.99      OK             Élevée
243              54.00   1012.18        875.00  ERREUR             Élevée
246              65.68   1009.70        198.65      OK             Élevée
251              85.77   1013.56        237.21  ALERTE             Élevée
257              66.32   1013.54        254.67      OK             Élevée
264              71.35   1018.92        308.66      OK             Élevée
274              67.19   1009.71        329.78      OK             Élevée
280              73.35   1021.40        187.98      OK             Élevée
322              53.58   1013.05        396.90  ALERTE             Élevée
356              60.73   1022.32        321.75      OK             Élevée
362              63.47   1017.40        248.36      OK             Élevée
385              73.95   1007.24        162.39      OK             Élevée
398              93.57   1015.93        306.24  ALERTE             Élevée
401              63.10    996.56        271.51      OK             Élevée
404              64.55    997.31        311.77      OK             Élevée
417              65.98   1005.48        256.18      OK             Élevée
437              41.80    996.99        255.56  ALERTE             Élevée
438              67.77   1016.88        181.51  ALERTE             Élevée
447              69.20   1016.10        172.49      OK             Élevée
488              51.02   1007.70        366.53  ALERTE             Élevée
492              62.06   1009.35        299.69      OK             Élevée
500              52.13   1004.23        262.66      OK             Élevée
502              81.51   1026.79        271.92  ERREUR             Élevée
505              64.23   1011.42        179.84      OK             Élevée
520              53.28   1010.05        195.37  ALERTE             Élevée
541              76.00   1011.94        224.01      OK             Élevée
558              36.33   1010.46        272.59      OK             Élevée
    id_mesure           date_heure id_capteur batiment  temperature  \
47      M0082  2026-01-08 09:00:00       C010     B004        32.46
88      M0288  2026-01-16 23:00:00       C012     B004        30.06
129     M0592  2026-01-29 15:00:00       C004     B002        33.60
145     M0503  2026-01-25 22:00:00       C011     B004        30.57
165     M0323  2026-01-18 10:00:00       C011     B004        33.01
168     M0276  2026-01-16 11:00:00       C012     B004        30.39
210     M0588  2026-01-29 11:00:00       C012     B004        31.51
251     M0114  2026-01-09 17:00:00       C006     B002        31.85
264     M0191  2026-01-12 22:00:00       C011     B004        30.75
280     M0585  2026-01-29 08:00:00       C009     B003        31.30
385     M0126  2026-01-10 05:00:00       C006     B002        30.09
398     M0514  2026-01-26 09:00:00       C010     B004        30.48
502     M0048  2026-01-06 23:00:00       C012     B004        58.70
541     M0202  2026-01-13 09:00:00       C010     B004        30.86

     humidite_relative  pression  consommation    etat niveau_temperature
47               72.31   1000.42        276.99  ALERTE             Élevée
88               75.30   1014.47        323.32      OK             Élevée
129              79.80   1021.96        212.55  ALERTE             Élevée
145              71.26   1002.88        359.97      OK             Élevée
165              73.24   1014.36        260.24  ALERTE             Élevée
168              71.14   1017.79        303.38      OK             Élevée
210              72.49   1018.21        307.97      OK             Élevée
251              85.77   1013.56        237.21  ALERTE             Élevée
264              71.35   1018.92        308.66      OK             Élevée
280              73.35   1021.40        187.98      OK             Élevée
385              73.95   1007.24        162.39      OK             Élevée
398              93.57   1015.93        306.24  ALERTE             Élevée
502              81.51   1026.79        271.92  ERREUR             Élevée
541              76.00   1011.94        224.01      OK             Élevée

Partie 7 : Tri